version: '3.8'
services:
  db:
    image: postgres
    restart: always
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '54320:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local